//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 12:50:52 PM EDT 
//


package com.ceb.ppm.schema.mfw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BlockerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BlockerType">
 *   &lt;complexContent>
 *     &lt;extension base="{}DomainObjectType">
 *       &lt;sequence>
 *         &lt;element name="BlockedBy" type="{}UserType" minOccurs="0"/>
 *         &lt;element name="WorkProduct" type="{}ArtifactType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BlockerType", propOrder = {
    "blockedBy",
    "workProduct"
})
public class BlockerType
    extends DomainObjectType
{

    @XmlElement(name = "BlockedBy")
    protected UserType blockedBy;
    @XmlElement(name = "WorkProduct")
    protected ArtifactType workProduct;

    /**
     * Gets the value of the blockedBy property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getBlockedBy() {
        return blockedBy;
    }

    /**
     * Sets the value of the blockedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setBlockedBy(UserType value) {
        this.blockedBy = value;
    }

    /**
     * Gets the value of the workProduct property.
     * 
     * @return
     *     possible object is
     *     {@link ArtifactType }
     *     
     */
    public ArtifactType getWorkProduct() {
        return workProduct;
    }

    /**
     * Sets the value of the workProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArtifactType }
     *     
     */
    public void setWorkProduct(ArtifactType value) {
        this.workProduct = value;
    }

}
