//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 12:50:52 PM EDT 
//


package com.ceb.ppm.schema.mfw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateResultType">
 *   &lt;complexContent>
 *     &lt;extension base="{}OperationResultType">
 *       &lt;sequence>
 *         &lt;element name="Object" type="{}DomainObjectType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateResultType", propOrder = {
    "object"
})
public class CreateResultType
    extends OperationResultType
{

    @XmlElement(name = "Object")
    protected DomainObjectType object;

    /**
     * Gets the value of the object property.
     * 
     * @return
     *     possible object is
     *     {@link DomainObjectType }
     *     
     */
    public DomainObjectType getObject() {
        return object;
    }

    /**
     * Sets the value of the object property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainObjectType }
     *     
     */
    public void setObject(DomainObjectType value) {
        this.object = value;
    }

}
