//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 12:50:52 PM EDT 
//


package com.ceb.ppm.schema.mfw;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ceb.ppm.schema.mfw package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _User_QNAME = new QName("", "User");
    private final static QName _Attachment_QNAME = new QName("", "Attachment");
    private final static QName _Workspace_QNAME = new QName("", "Workspace");
    private final static QName _RevisionHistory_QNAME = new QName("", "RevisionHistory");
    private final static QName _TestCaseStep_QNAME = new QName("", "TestCaseStep");
    private final static QName _AttributeDefinition_QNAME = new QName("", "AttributeDefinition");
    private final static QName _BuildMetric_QNAME = new QName("", "BuildMetric");
    private final static QName _AttachmentContent_QNAME = new QName("", "AttachmentContent");
    private final static QName _Build_QNAME = new QName("", "Build");
    private final static QName _Requirement_QNAME = new QName("", "Requirement");
    private final static QName _Tag_QNAME = new QName("", "Tag");
    private final static QName _IterationCumulativeFlowData_QNAME = new QName("", "IterationCumulativeFlowData");
    private final static QName _Project_QNAME = new QName("", "Project");
    private final static QName _Blocker_QNAME = new QName("", "Blocker");
    private final static QName _ScopedAttributeDefinition_QNAME = new QName("", "ScopedAttributeDefinition");
    private final static QName _WebLinkDefinition_QNAME = new QName("", "WebLinkDefinition");
    private final static QName _WorkspaceConfiguration_QNAME = new QName("", "WorkspaceConfiguration");
    private final static QName _Change_QNAME = new QName("", "Change");
    private final static QName _WorkspaceDomainObject_QNAME = new QName("", "WorkspaceDomainObject");
    private final static QName _ConversationPost_QNAME = new QName("", "ConversationPost");
    private final static QName _BuildDefinition_QNAME = new QName("", "BuildDefinition");
    private final static QName _DomainObject_QNAME = new QName("", "DomainObject");
    private final static QName _Release_QNAME = new QName("", "Release");
    private final static QName _Defect_QNAME = new QName("", "Defect");
    private final static QName _Artifact_QNAME = new QName("", "Artifact");
    private final static QName _Subscription_QNAME = new QName("", "Subscription");
    private final static QName _TestCase_QNAME = new QName("", "TestCase");
    private final static QName _Task_QNAME = new QName("", "Task");
    private final static QName _TimeEntryItem_QNAME = new QName("", "TimeEntryItem");
    private final static QName _ArtifactNotification_QNAME = new QName("", "ArtifactNotification");
    private final static QName _UserPermission_QNAME = new QName("", "UserPermission");
    private final static QName _QueryResult_QNAME = new QName("", "QueryResult");
    private final static QName _SCMRepository_QNAME = new QName("", "SCMRepository");
    private final static QName _WorkspacePermission_QNAME = new QName("", "WorkspacePermission");
    private final static QName _Iteration_QNAME = new QName("", "Iteration");
    private final static QName _ProjectPermission_QNAME = new QName("", "ProjectPermission");
    private final static QName _TypeDefinition_QNAME = new QName("", "TypeDefinition");
    private final static QName _Changeset_QNAME = new QName("", "Changeset");
    private final static QName _DefectSuite_QNAME = new QName("", "DefectSuite");
    private final static QName _AllowedAttributeValue_QNAME = new QName("", "AllowedAttributeValue");
    private final static QName _CumulativeFlowData_QNAME = new QName("", "CumulativeFlowData");
    private final static QName _ReleaseCumulativeFlowData_QNAME = new QName("", "ReleaseCumulativeFlowData");
    private final static QName _AllowedQueryOperator_QNAME = new QName("", "AllowedQueryOperator");
    private final static QName _TestCaseResult_QNAME = new QName("", "TestCaseResult");
    private final static QName _PersistableObject_QNAME = new QName("", "PersistableObject");
    private final static QName _OperationResult_QNAME = new QName("", "OperationResult");
    private final static QName _BuildMetricDefinition_QNAME = new QName("", "BuildMetricDefinition");
    private final static QName _HierarchicalRequirement_QNAME = new QName("", "HierarchicalRequirement");
    private final static QName _Revision_QNAME = new QName("", "Revision");
    private final static QName _CreateResult_QNAME = new QName("", "CreateResult");
    private final static QName _TimeEntryValue_QNAME = new QName("", "TimeEntryValue");
    private final static QName _UserProfile_QNAME = new QName("", "UserProfile");
    private final static QName _UserIterationCapacity_QNAME = new QName("", "UserIterationCapacity");
    private final static QName _Preference_QNAME = new QName("", "Preference");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ceb.ppm.schema.mfw
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DefectType }
     * 
     */
    public DefectType createDefectType() {
        return new DefectType();
    }

    /**
     * Create an instance of {@link TestCaseStepsType }
     * 
     */
    public TestCaseStepsType createTestCaseStepsType() {
        return new TestCaseStepsType();
    }

    /**
     * Create an instance of {@link ChangesetType }
     * 
     */
    public ChangesetType createChangesetType() {
        return new ChangesetType();
    }

    /**
     * Create an instance of {@link TestCaseResultsType }
     * 
     */
    public TestCaseResultsType createTestCaseResultsType() {
        return new TestCaseResultsType();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link TestCaseResultType }
     * 
     */
    public TestCaseResultType createTestCaseResultType() {
        return new TestCaseResultType();
    }

    /**
     * Create an instance of {@link WorkspacePermissionType }
     * 
     */
    public WorkspacePermissionType createWorkspacePermissionType() {
        return new WorkspacePermissionType();
    }

    /**
     * Create an instance of {@link SubscriptionWorkspacesType }
     * 
     */
    public SubscriptionWorkspacesType createSubscriptionWorkspacesType() {
        return new SubscriptionWorkspacesType();
    }

    /**
     * Create an instance of {@link OperationResultType }
     * 
     */
    public OperationResultType createOperationResultType() {
        return new OperationResultType();
    }

    /**
     * Create an instance of {@link ReleaseCumulativeFlowDataType }
     * 
     */
    public ReleaseCumulativeFlowDataType createReleaseCumulativeFlowDataType() {
        return new ReleaseCumulativeFlowDataType();
    }

    /**
     * Create an instance of {@link UserTeamMembershipsType }
     * 
     */
    public UserTeamMembershipsType createUserTeamMembershipsType() {
        return new UserTeamMembershipsType();
    }

    /**
     * Create an instance of {@link IterationCumulativeFlowDataType }
     * 
     */
    public IterationCumulativeFlowDataType createIterationCumulativeFlowDataType() {
        return new IterationCumulativeFlowDataType();
    }

    /**
     * Create an instance of {@link AttachmentType }
     * 
     */
    public AttachmentType createAttachmentType() {
        return new AttachmentType();
    }

    /**
     * Create an instance of {@link RevisionHistoryType }
     * 
     */
    public RevisionHistoryType createRevisionHistoryType() {
        return new RevisionHistoryType();
    }

    /**
     * Create an instance of {@link BuildType }
     * 
     */
    public BuildType createBuildType() {
        return new BuildType();
    }

    /**
     * Create an instance of {@link HierarchicalRequirementSuccessorsType }
     * 
     */
    public HierarchicalRequirementSuccessorsType createHierarchicalRequirementSuccessorsType() {
        return new HierarchicalRequirementSuccessorsType();
    }

    /**
     * Create an instance of {@link DefectTasksType }
     * 
     */
    public DefectTasksType createDefectTasksType() {
        return new DefectTasksType();
    }

    /**
     * Create an instance of {@link TimeEntryItemType }
     * 
     */
    public TimeEntryItemType createTimeEntryItemType() {
        return new TimeEntryItemType();
    }

    /**
     * Create an instance of {@link BuildDefinitionBuildsType }
     * 
     */
    public BuildDefinitionBuildsType createBuildDefinitionBuildsType() {
        return new BuildDefinitionBuildsType();
    }

    /**
     * Create an instance of {@link TypeDefinitionAttributesType }
     * 
     */
    public TypeDefinitionAttributesType createTypeDefinitionAttributesType() {
        return new TypeDefinitionAttributesType();
    }

    /**
     * Create an instance of {@link TestCaseType }
     * 
     */
    public TestCaseType createTestCaseType() {
        return new TestCaseType();
    }

    /**
     * Create an instance of {@link SCMRepositoryProjectsType }
     * 
     */
    public SCMRepositoryProjectsType createSCMRepositoryProjectsType() {
        return new SCMRepositoryProjectsType();
    }

    /**
     * Create an instance of {@link DefectSuiteTasksType }
     * 
     */
    public DefectSuiteTasksType createDefectSuiteTasksType() {
        return new DefectSuiteTasksType();
    }

    /**
     * Create an instance of {@link ProjectIterationsType }
     * 
     */
    public ProjectIterationsType createProjectIterationsType() {
        return new ProjectIterationsType();
    }

    /**
     * Create an instance of {@link RevisionHistoryRevisionsType }
     * 
     */
    public RevisionHistoryRevisionsType createRevisionHistoryRevisionsType() {
        return new RevisionHistoryRevisionsType();
    }

    /**
     * Create an instance of {@link PreferenceType }
     * 
     */
    public PreferenceType createPreferenceType() {
        return new PreferenceType();
    }

    /**
     * Create an instance of {@link RevisionType }
     * 
     */
    public RevisionType createRevisionType() {
        return new RevisionType();
    }

    /**
     * Create an instance of {@link ArtifactDiscussionType }
     * 
     */
    public ArtifactDiscussionType createArtifactDiscussionType() {
        return new ArtifactDiscussionType();
    }

    /**
     * Create an instance of {@link HierarchicalRequirementType }
     * 
     */
    public HierarchicalRequirementType createHierarchicalRequirementType() {
        return new HierarchicalRequirementType();
    }

    /**
     * Create an instance of {@link AllowedQueryOperatorType }
     * 
     */
    public AllowedQueryOperatorType createAllowedQueryOperatorType() {
        return new AllowedQueryOperatorType();
    }

    /**
     * Create an instance of {@link TypeDefinitionType }
     * 
     */
    public TypeDefinitionType createTypeDefinitionType() {
        return new TypeDefinitionType();
    }

    /**
     * Create an instance of {@link BuildChangesetsType }
     * 
     */
    public BuildChangesetsType createBuildChangesetsType() {
        return new BuildChangesetsType();
    }

    /**
     * Create an instance of {@link WorkspaceDomainObjectType }
     * 
     */
    public WorkspaceDomainObjectType createWorkspaceDomainObjectType() {
        return new WorkspaceDomainObjectType();
    }

    /**
     * Create an instance of {@link AttachmentContentType }
     * 
     */
    public AttachmentContentType createAttachmentContentType() {
        return new AttachmentContentType();
    }

    /**
     * Create an instance of {@link AttributeDefinitionAllowedQueryOperatorsType }
     * 
     */
    public AttributeDefinitionAllowedQueryOperatorsType createAttributeDefinitionAllowedQueryOperatorsType() {
        return new AttributeDefinitionAllowedQueryOperatorsType();
    }

    /**
     * Create an instance of {@link IterationUserIterationCapacitiesType }
     * 
     */
    public IterationUserIterationCapacitiesType createIterationUserIterationCapacitiesType() {
        return new IterationUserIterationCapacitiesType();
    }

    /**
     * Create an instance of {@link ArtifactType }
     * 
     */
    public ArtifactType createArtifactType() {
        return new ArtifactType();
    }

    /**
     * Create an instance of {@link UserPermissionType }
     * 
     */
    public UserPermissionType createUserPermissionType() {
        return new UserPermissionType();
    }

    /**
     * Create an instance of {@link WebLink }
     * 
     */
    public WebLink createWebLink() {
        return new WebLink();
    }

    /**
     * Create an instance of {@link ChangesetChangesType }
     * 
     */
    public ChangesetChangesType createChangesetChangesType() {
        return new ChangesetChangesType();
    }

    /**
     * Create an instance of {@link DefectSuiteType }
     * 
     */
    public DefectSuiteType createDefectSuiteType() {
        return new DefectSuiteType();
    }

    /**
     * Create an instance of {@link DefectDuplicatesType }
     * 
     */
    public DefectDuplicatesType createDefectDuplicatesType() {
        return new DefectDuplicatesType();
    }

    /**
     * Create an instance of {@link DefectSuiteDefectsType }
     * 
     */
    public DefectSuiteDefectsType createDefectSuiteDefectsType() {
        return new DefectSuiteDefectsType();
    }

    /**
     * Create an instance of {@link WorkspaceProjectsType }
     * 
     */
    public WorkspaceProjectsType createWorkspaceProjectsType() {
        return new WorkspaceProjectsType();
    }

    /**
     * Create an instance of {@link TestCaseAttachmentsType }
     * 
     */
    public TestCaseAttachmentsType createTestCaseAttachmentsType() {
        return new TestCaseAttachmentsType();
    }

    /**
     * Create an instance of {@link CumulativeFlowDataType }
     * 
     */
    public CumulativeFlowDataType createCumulativeFlowDataType() {
        return new CumulativeFlowDataType();
    }

    /**
     * Create an instance of {@link TestCaseStepType }
     * 
     */
    public TestCaseStepType createTestCaseStepType() {
        return new TestCaseStepType();
    }

    /**
     * Create an instance of {@link ProjectPermissionType }
     * 
     */
    public ProjectPermissionType createProjectPermissionType() {
        return new ProjectPermissionType();
    }

    /**
     * Create an instance of {@link DefectTestCasesType }
     * 
     */
    public DefectTestCasesType createDefectTestCasesType() {
        return new DefectTestCasesType();
    }

    /**
     * Create an instance of {@link ConversationPostType }
     * 
     */
    public ConversationPostType createConversationPostType() {
        return new ConversationPostType();
    }

    /**
     * Create an instance of {@link ArtifactTagsType }
     * 
     */
    public ArtifactTagsType createArtifactTagsType() {
        return new ArtifactTagsType();
    }

    /**
     * Create an instance of {@link ArtifactChangesetsType }
     * 
     */
    public ArtifactChangesetsType createArtifactChangesetsType() {
        return new ArtifactChangesetsType();
    }

    /**
     * Create an instance of {@link HierarchicalRequirementChildrenType }
     * 
     */
    public HierarchicalRequirementChildrenType createHierarchicalRequirementChildrenType() {
        return new HierarchicalRequirementChildrenType();
    }

    /**
     * Create an instance of {@link ChangesetBuildsType }
     * 
     */
    public ChangesetBuildsType createChangesetBuildsType() {
        return new ChangesetBuildsType();
    }

    /**
     * Create an instance of {@link QueryResultType }
     * 
     */
    public QueryResultType createQueryResultType() {
        return new QueryResultType();
    }

    /**
     * Create an instance of {@link ReleaseType }
     * 
     */
    public ReleaseType createReleaseType() {
        return new ReleaseType();
    }

    /**
     * Create an instance of {@link OperationResultErrorsType }
     * 
     */
    public OperationResultErrorsType createOperationResultErrorsType() {
        return new OperationResultErrorsType();
    }

    /**
     * Create an instance of {@link OperationResultWarningsType }
     * 
     */
    public OperationResultWarningsType createOperationResultWarningsType() {
        return new OperationResultWarningsType();
    }

    /**
     * Create an instance of {@link BuildDefinitionType }
     * 
     */
    public BuildDefinitionType createBuildDefinitionType() {
        return new BuildDefinitionType();
    }

    /**
     * Create an instance of {@link AllowedAttributeValueType }
     * 
     */
    public AllowedAttributeValueType createAllowedAttributeValueType() {
        return new AllowedAttributeValueType();
    }

    /**
     * Create an instance of {@link TaskAttachmentsType }
     * 
     */
    public TaskAttachmentsType createTaskAttachmentsType() {
        return new TaskAttachmentsType();
    }

    /**
     * Create an instance of {@link WSObject }
     * 
     */
    public WSObject createWSObject() {
        return new WSObject();
    }

    /**
     * Create an instance of {@link BuildMetricDefinitionType }
     * 
     */
    public BuildMetricDefinitionType createBuildMetricDefinitionType() {
        return new BuildMetricDefinitionType();
    }

    /**
     * Create an instance of {@link RequirementType }
     * 
     */
    public RequirementType createRequirementType() {
        return new RequirementType();
    }

    /**
     * Create an instance of {@link TimeEntryValueType }
     * 
     */
    public TimeEntryValueType createTimeEntryValueType() {
        return new TimeEntryValueType();
    }

    /**
     * Create an instance of {@link UserProfileType }
     * 
     */
    public UserProfileType createUserProfileType() {
        return new UserProfileType();
    }

    /**
     * Create an instance of {@link HierarchicalRequirementTestCasesType }
     * 
     */
    public HierarchicalRequirementTestCasesType createHierarchicalRequirementTestCasesType() {
        return new HierarchicalRequirementTestCasesType();
    }

    /**
     * Create an instance of {@link TimeEntryItemValuesType }
     * 
     */
    public TimeEntryItemValuesType createTimeEntryItemValuesType() {
        return new TimeEntryItemValuesType();
    }

    /**
     * Create an instance of {@link HierarchicalRequirementPredecessorsType }
     * 
     */
    public HierarchicalRequirementPredecessorsType createHierarchicalRequirementPredecessorsType() {
        return new HierarchicalRequirementPredecessorsType();
    }

    /**
     * Create an instance of {@link SCMRepositoryType }
     * 
     */
    public SCMRepositoryType createSCMRepositoryType() {
        return new SCMRepositoryType();
    }

    /**
     * Create an instance of {@link PersistableObjectType }
     * 
     */
    public PersistableObjectType createPersistableObjectType() {
        return new PersistableObjectType();
    }

    /**
     * Create an instance of {@link BuildMetricType }
     * 
     */
    public BuildMetricType createBuildMetricType() {
        return new BuildMetricType();
    }

    /**
     * Create an instance of {@link ProjectBuildDefinitionsType }
     * 
     */
    public ProjectBuildDefinitionsType createProjectBuildDefinitionsType() {
        return new ProjectBuildDefinitionsType();
    }

    /**
     * Create an instance of {@link ProjectChildrenType }
     * 
     */
    public ProjectChildrenType createProjectChildrenType() {
        return new ProjectChildrenType();
    }

    /**
     * Create an instance of {@link DomainObjectType }
     * 
     */
    public DomainObjectType createDomainObjectType() {
        return new DomainObjectType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link HierarchicalRequirementDefectsType }
     * 
     */
    public HierarchicalRequirementDefectsType createHierarchicalRequirementDefectsType() {
        return new HierarchicalRequirementDefectsType();
    }

    /**
     * Create an instance of {@link HierarchicalRequirementTasksType }
     * 
     */
    public HierarchicalRequirementTasksType createHierarchicalRequirementTasksType() {
        return new HierarchicalRequirementTasksType();
    }

    /**
     * Create an instance of {@link ArtifactNotificationType }
     * 
     */
    public ArtifactNotificationType createArtifactNotificationType() {
        return new ArtifactNotificationType();
    }

    /**
     * Create an instance of {@link BuildDefinitionProjectsType }
     * 
     */
    public BuildDefinitionProjectsType createBuildDefinitionProjectsType() {
        return new BuildDefinitionProjectsType();
    }

    /**
     * Create an instance of {@link ProjectEditorsType }
     * 
     */
    public ProjectEditorsType createProjectEditorsType() {
        return new ProjectEditorsType();
    }

    /**
     * Create an instance of {@link ProjectType }
     * 
     */
    public ProjectType createProjectType() {
        return new ProjectType();
    }

    /**
     * Create an instance of {@link DefectSuiteAttachmentsType }
     * 
     */
    public DefectSuiteAttachmentsType createDefectSuiteAttachmentsType() {
        return new DefectSuiteAttachmentsType();
    }

    /**
     * Create an instance of {@link QueryResultResultsType }
     * 
     */
    public QueryResultResultsType createQueryResultResultsType() {
        return new QueryResultResultsType();
    }

    /**
     * Create an instance of {@link IterationType }
     * 
     */
    public IterationType createIterationType() {
        return new IterationType();
    }

    /**
     * Create an instance of {@link DefectAttachmentsType }
     * 
     */
    public DefectAttachmentsType createDefectAttachmentsType() {
        return new DefectAttachmentsType();
    }

    /**
     * Create an instance of {@link WorkspaceType }
     * 
     */
    public WorkspaceType createWorkspaceType() {
        return new WorkspaceType();
    }

    /**
     * Create an instance of {@link RequirementAttachmentsType }
     * 
     */
    public RequirementAttachmentsType createRequirementAttachmentsType() {
        return new RequirementAttachmentsType();
    }

    /**
     * Create an instance of {@link TestCaseResultAttachmentsType }
     * 
     */
    public TestCaseResultAttachmentsType createTestCaseResultAttachmentsType() {
        return new TestCaseResultAttachmentsType();
    }

    /**
     * Create an instance of {@link ChangesetArtifactsType }
     * 
     */
    public ChangesetArtifactsType createChangesetArtifactsType() {
        return new ChangesetArtifactsType();
    }

    /**
     * Create an instance of {@link WorkspaceTypeDefinitionsType }
     * 
     */
    public WorkspaceTypeDefinitionsType createWorkspaceTypeDefinitionsType() {
        return new WorkspaceTypeDefinitionsType();
    }

    /**
     * Create an instance of {@link SubscriptionType }
     * 
     */
    public SubscriptionType createSubscriptionType() {
        return new SubscriptionType();
    }

    /**
     * Create an instance of {@link CreateResultType }
     * 
     */
    public CreateResultType createCreateResultType() {
        return new CreateResultType();
    }

    /**
     * Create an instance of {@link BlockerType }
     * 
     */
    public BlockerType createBlockerType() {
        return new BlockerType();
    }

    /**
     * Create an instance of {@link ScopedAttributeDefinitionType }
     * 
     */
    public ScopedAttributeDefinitionType createScopedAttributeDefinitionType() {
        return new ScopedAttributeDefinitionType();
    }

    /**
     * Create an instance of {@link WebLinkDefinitionType }
     * 
     */
    public WebLinkDefinitionType createWebLinkDefinitionType() {
        return new WebLinkDefinitionType();
    }

    /**
     * Create an instance of {@link WorkspaceConfigurationType }
     * 
     */
    public WorkspaceConfigurationType createWorkspaceConfigurationType() {
        return new WorkspaceConfigurationType();
    }

    /**
     * Create an instance of {@link ChangeType }
     * 
     */
    public ChangeType createChangeType() {
        return new ChangeType();
    }

    /**
     * Create an instance of {@link ProjectReleasesType }
     * 
     */
    public ProjectReleasesType createProjectReleasesType() {
        return new ProjectReleasesType();
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
        return new TaskType();
    }

    /**
     * Create an instance of {@link AttributeDefinitionType }
     * 
     */
    public AttributeDefinitionType createAttributeDefinitionType() {
        return new AttributeDefinitionType();
    }

    /**
     * Create an instance of {@link UserIterationCapacityType }
     * 
     */
    public UserIterationCapacityType createUserIterationCapacityType() {
        return new UserIterationCapacityType();
    }

    /**
     * Create an instance of {@link UserUserPermissionsType }
     * 
     */
    public UserUserPermissionsType createUserUserPermissionsType() {
        return new UserUserPermissionsType();
    }

    /**
     * Create an instance of {@link AttributeDefinitionAllowedValuesType }
     * 
     */
    public AttributeDefinitionAllowedValuesType createAttributeDefinitionAllowedValuesType() {
        return new AttributeDefinitionAllowedValuesType();
    }

    /**
     * Create an instance of {@link ProjectTeamMembersType }
     * 
     */
    public ProjectTeamMembersType createProjectTeamMembersType() {
        return new ProjectTeamMembersType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "User")
    public JAXBElement<UserType> createUser(UserType value) {
        return new JAXBElement<UserType>(_User_QNAME, UserType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Attachment")
    public JAXBElement<AttachmentType> createAttachment(AttachmentType value) {
        return new JAXBElement<AttachmentType>(_Attachment_QNAME, AttachmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkspaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Workspace")
    public JAXBElement<WorkspaceType> createWorkspace(WorkspaceType value) {
        return new JAXBElement<WorkspaceType>(_Workspace_QNAME, WorkspaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RevisionHistoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RevisionHistory")
    public JAXBElement<RevisionHistoryType> createRevisionHistory(RevisionHistoryType value) {
        return new JAXBElement<RevisionHistoryType>(_RevisionHistory_QNAME, RevisionHistoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestCaseStepType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TestCaseStep")
    public JAXBElement<TestCaseStepType> createTestCaseStep(TestCaseStepType value) {
        return new JAXBElement<TestCaseStepType>(_TestCaseStep_QNAME, TestCaseStepType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AttributeDefinition")
    public JAXBElement<AttributeDefinitionType> createAttributeDefinition(AttributeDefinitionType value) {
        return new JAXBElement<AttributeDefinitionType>(_AttributeDefinition_QNAME, AttributeDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuildMetricType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BuildMetric")
    public JAXBElement<BuildMetricType> createBuildMetric(BuildMetricType value) {
        return new JAXBElement<BuildMetricType>(_BuildMetric_QNAME, BuildMetricType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AttachmentContent")
    public JAXBElement<AttachmentContentType> createAttachmentContent(AttachmentContentType value) {
        return new JAXBElement<AttachmentContentType>(_AttachmentContent_QNAME, AttachmentContentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuildType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Build")
    public JAXBElement<BuildType> createBuild(BuildType value) {
        return new JAXBElement<BuildType>(_Build_QNAME, BuildType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequirementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Requirement")
    public JAXBElement<RequirementType> createRequirement(RequirementType value) {
        return new JAXBElement<RequirementType>(_Requirement_QNAME, RequirementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tag")
    public JAXBElement<TagType> createTag(TagType value) {
        return new JAXBElement<TagType>(_Tag_QNAME, TagType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IterationCumulativeFlowDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IterationCumulativeFlowData")
    public JAXBElement<IterationCumulativeFlowDataType> createIterationCumulativeFlowData(IterationCumulativeFlowDataType value) {
        return new JAXBElement<IterationCumulativeFlowDataType>(_IterationCumulativeFlowData_QNAME, IterationCumulativeFlowDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Project")
    public JAXBElement<ProjectType> createProject(ProjectType value) {
        return new JAXBElement<ProjectType>(_Project_QNAME, ProjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Blocker")
    public JAXBElement<BlockerType> createBlocker(BlockerType value) {
        return new JAXBElement<BlockerType>(_Blocker_QNAME, BlockerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScopedAttributeDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ScopedAttributeDefinition")
    public JAXBElement<ScopedAttributeDefinitionType> createScopedAttributeDefinition(ScopedAttributeDefinitionType value) {
        return new JAXBElement<ScopedAttributeDefinitionType>(_ScopedAttributeDefinition_QNAME, ScopedAttributeDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebLinkDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WebLinkDefinition")
    public JAXBElement<WebLinkDefinitionType> createWebLinkDefinition(WebLinkDefinitionType value) {
        return new JAXBElement<WebLinkDefinitionType>(_WebLinkDefinition_QNAME, WebLinkDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkspaceConfigurationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WorkspaceConfiguration")
    public JAXBElement<WorkspaceConfigurationType> createWorkspaceConfiguration(WorkspaceConfigurationType value) {
        return new JAXBElement<WorkspaceConfigurationType>(_WorkspaceConfiguration_QNAME, WorkspaceConfigurationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Change")
    public JAXBElement<ChangeType> createChange(ChangeType value) {
        return new JAXBElement<ChangeType>(_Change_QNAME, ChangeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkspaceDomainObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WorkspaceDomainObject")
    public JAXBElement<WorkspaceDomainObjectType> createWorkspaceDomainObject(WorkspaceDomainObjectType value) {
        return new JAXBElement<WorkspaceDomainObjectType>(_WorkspaceDomainObject_QNAME, WorkspaceDomainObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConversationPostType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConversationPost")
    public JAXBElement<ConversationPostType> createConversationPost(ConversationPostType value) {
        return new JAXBElement<ConversationPostType>(_ConversationPost_QNAME, ConversationPostType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuildDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BuildDefinition")
    public JAXBElement<BuildDefinitionType> createBuildDefinition(BuildDefinitionType value) {
        return new JAXBElement<BuildDefinitionType>(_BuildDefinition_QNAME, BuildDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DomainObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DomainObject")
    public JAXBElement<DomainObjectType> createDomainObject(DomainObjectType value) {
        return new JAXBElement<DomainObjectType>(_DomainObject_QNAME, DomainObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReleaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Release")
    public JAXBElement<ReleaseType> createRelease(ReleaseType value) {
        return new JAXBElement<ReleaseType>(_Release_QNAME, ReleaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Defect")
    public JAXBElement<DefectType> createDefect(DefectType value) {
        return new JAXBElement<DefectType>(_Defect_QNAME, DefectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArtifactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Artifact")
    public JAXBElement<ArtifactType> createArtifact(ArtifactType value) {
        return new JAXBElement<ArtifactType>(_Artifact_QNAME, ArtifactType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubscriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Subscription")
    public JAXBElement<SubscriptionType> createSubscription(SubscriptionType value) {
        return new JAXBElement<SubscriptionType>(_Subscription_QNAME, SubscriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestCaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TestCase")
    public JAXBElement<TestCaseType> createTestCase(TestCaseType value) {
        return new JAXBElement<TestCaseType>(_TestCase_QNAME, TestCaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaskType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Task")
    public JAXBElement<TaskType> createTask(TaskType value) {
        return new JAXBElement<TaskType>(_Task_QNAME, TaskType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeEntryItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TimeEntryItem")
    public JAXBElement<TimeEntryItemType> createTimeEntryItem(TimeEntryItemType value) {
        return new JAXBElement<TimeEntryItemType>(_TimeEntryItem_QNAME, TimeEntryItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArtifactNotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArtifactNotification")
    public JAXBElement<ArtifactNotificationType> createArtifactNotification(ArtifactNotificationType value) {
        return new JAXBElement<ArtifactNotificationType>(_ArtifactNotification_QNAME, ArtifactNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserPermissionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserPermission")
    public JAXBElement<UserPermissionType> createUserPermission(UserPermissionType value) {
        return new JAXBElement<UserPermissionType>(_UserPermission_QNAME, UserPermissionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QueryResult")
    public JAXBElement<QueryResultType> createQueryResult(QueryResultType value) {
        return new JAXBElement<QueryResultType>(_QueryResult_QNAME, QueryResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SCMRepositoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SCMRepository")
    public JAXBElement<SCMRepositoryType> createSCMRepository(SCMRepositoryType value) {
        return new JAXBElement<SCMRepositoryType>(_SCMRepository_QNAME, SCMRepositoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkspacePermissionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WorkspacePermission")
    public JAXBElement<WorkspacePermissionType> createWorkspacePermission(WorkspacePermissionType value) {
        return new JAXBElement<WorkspacePermissionType>(_WorkspacePermission_QNAME, WorkspacePermissionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IterationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Iteration")
    public JAXBElement<IterationType> createIteration(IterationType value) {
        return new JAXBElement<IterationType>(_Iteration_QNAME, IterationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProjectPermissionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProjectPermission")
    public JAXBElement<ProjectPermissionType> createProjectPermission(ProjectPermissionType value) {
        return new JAXBElement<ProjectPermissionType>(_ProjectPermission_QNAME, ProjectPermissionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TypeDefinition")
    public JAXBElement<TypeDefinitionType> createTypeDefinition(TypeDefinitionType value) {
        return new JAXBElement<TypeDefinitionType>(_TypeDefinition_QNAME, TypeDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangesetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Changeset")
    public JAXBElement<ChangesetType> createChangeset(ChangesetType value) {
        return new JAXBElement<ChangesetType>(_Changeset_QNAME, ChangesetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefectSuiteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DefectSuite")
    public JAXBElement<DefectSuiteType> createDefectSuite(DefectSuiteType value) {
        return new JAXBElement<DefectSuiteType>(_DefectSuite_QNAME, DefectSuiteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AllowedAttributeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AllowedAttributeValue")
    public JAXBElement<AllowedAttributeValueType> createAllowedAttributeValue(AllowedAttributeValueType value) {
        return new JAXBElement<AllowedAttributeValueType>(_AllowedAttributeValue_QNAME, AllowedAttributeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CumulativeFlowDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CumulativeFlowData")
    public JAXBElement<CumulativeFlowDataType> createCumulativeFlowData(CumulativeFlowDataType value) {
        return new JAXBElement<CumulativeFlowDataType>(_CumulativeFlowData_QNAME, CumulativeFlowDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReleaseCumulativeFlowDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReleaseCumulativeFlowData")
    public JAXBElement<ReleaseCumulativeFlowDataType> createReleaseCumulativeFlowData(ReleaseCumulativeFlowDataType value) {
        return new JAXBElement<ReleaseCumulativeFlowDataType>(_ReleaseCumulativeFlowData_QNAME, ReleaseCumulativeFlowDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AllowedQueryOperatorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AllowedQueryOperator")
    public JAXBElement<AllowedQueryOperatorType> createAllowedQueryOperator(AllowedQueryOperatorType value) {
        return new JAXBElement<AllowedQueryOperatorType>(_AllowedQueryOperator_QNAME, AllowedQueryOperatorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestCaseResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TestCaseResult")
    public JAXBElement<TestCaseResultType> createTestCaseResult(TestCaseResultType value) {
        return new JAXBElement<TestCaseResultType>(_TestCaseResult_QNAME, TestCaseResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersistableObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PersistableObject")
    public JAXBElement<PersistableObjectType> createPersistableObject(PersistableObjectType value) {
        return new JAXBElement<PersistableObjectType>(_PersistableObject_QNAME, PersistableObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperationResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OperationResult")
    public JAXBElement<OperationResultType> createOperationResult(OperationResultType value) {
        return new JAXBElement<OperationResultType>(_OperationResult_QNAME, OperationResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuildMetricDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BuildMetricDefinition")
    public JAXBElement<BuildMetricDefinitionType> createBuildMetricDefinition(BuildMetricDefinitionType value) {
        return new JAXBElement<BuildMetricDefinitionType>(_BuildMetricDefinition_QNAME, BuildMetricDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HierarchicalRequirementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HierarchicalRequirement")
    public JAXBElement<HierarchicalRequirementType> createHierarchicalRequirement(HierarchicalRequirementType value) {
        return new JAXBElement<HierarchicalRequirementType>(_HierarchicalRequirement_QNAME, HierarchicalRequirementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RevisionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Revision")
    public JAXBElement<RevisionType> createRevision(RevisionType value) {
        return new JAXBElement<RevisionType>(_Revision_QNAME, RevisionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreateResult")
    public JAXBElement<CreateResultType> createCreateResult(CreateResultType value) {
        return new JAXBElement<CreateResultType>(_CreateResult_QNAME, CreateResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeEntryValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TimeEntryValue")
    public JAXBElement<TimeEntryValueType> createTimeEntryValue(TimeEntryValueType value) {
        return new JAXBElement<TimeEntryValueType>(_TimeEntryValue_QNAME, TimeEntryValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserProfileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserProfile")
    public JAXBElement<UserProfileType> createUserProfile(UserProfileType value) {
        return new JAXBElement<UserProfileType>(_UserProfile_QNAME, UserProfileType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserIterationCapacityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserIterationCapacity")
    public JAXBElement<UserIterationCapacityType> createUserIterationCapacity(UserIterationCapacityType value) {
        return new JAXBElement<UserIterationCapacityType>(_UserIterationCapacity_QNAME, UserIterationCapacityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PreferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Preference")
    public JAXBElement<PreferenceType> createPreference(PreferenceType value) {
        return new JAXBElement<PreferenceType>(_Preference_QNAME, PreferenceType.class, null, value);
    }

}
