//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 12:50:52 PM EDT 
//


package com.ceb.ppm.schema.mfw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{}WorkspaceDomainObjectType">
 *       &lt;sequence>
 *         &lt;element name="BuildDefinitions" type="{}ProjectBuildDefinitionsType" minOccurs="0"/>
 *         &lt;element name="Children" type="{}ProjectChildrenType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Editors" type="{}ProjectEditorsType" minOccurs="0"/>
 *         &lt;element name="Iterations" type="{}ProjectIterationsType" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Owner" type="{}UserType" minOccurs="0"/>
 *         &lt;element name="Parent" type="{}ProjectType" minOccurs="0"/>
 *         &lt;element name="Releases" type="{}ProjectReleasesType" minOccurs="0"/>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TeamMembers" type="{}ProjectTeamMembersType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProjectType", propOrder = {
    "buildDefinitions",
    "children",
    "description",
    "editors",
    "iterations",
    "name",
    "notes",
    "owner",
    "parent",
    "releases",
    "state",
    "teamMembers"
})
public class ProjectType
    extends WorkspaceDomainObjectType
{

    @XmlElement(name = "BuildDefinitions")
    protected ProjectBuildDefinitionsType buildDefinitions;
    @XmlElement(name = "Children")
    protected ProjectChildrenType children;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Editors")
    protected ProjectEditorsType editors;
    @XmlElement(name = "Iterations")
    protected ProjectIterationsType iterations;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Notes")
    protected String notes;
    @XmlElement(name = "Owner")
    protected UserType owner;
    @XmlElement(name = "Parent")
    protected ProjectType parent;
    @XmlElement(name = "Releases")
    protected ProjectReleasesType releases;
    @XmlElement(name = "State")
    protected String state;
    @XmlElement(name = "TeamMembers")
    protected ProjectTeamMembersType teamMembers;

    /**
     * Gets the value of the buildDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectBuildDefinitionsType }
     *     
     */
    public ProjectBuildDefinitionsType getBuildDefinitions() {
        return buildDefinitions;
    }

    /**
     * Sets the value of the buildDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectBuildDefinitionsType }
     *     
     */
    public void setBuildDefinitions(ProjectBuildDefinitionsType value) {
        this.buildDefinitions = value;
    }

    /**
     * Gets the value of the children property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectChildrenType }
     *     
     */
    public ProjectChildrenType getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectChildrenType }
     *     
     */
    public void setChildren(ProjectChildrenType value) {
        this.children = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the editors property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectEditorsType }
     *     
     */
    public ProjectEditorsType getEditors() {
        return editors;
    }

    /**
     * Sets the value of the editors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectEditorsType }
     *     
     */
    public void setEditors(ProjectEditorsType value) {
        this.editors = value;
    }

    /**
     * Gets the value of the iterations property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectIterationsType }
     *     
     */
    public ProjectIterationsType getIterations() {
        return iterations;
    }

    /**
     * Sets the value of the iterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectIterationsType }
     *     
     */
    public void setIterations(ProjectIterationsType value) {
        this.iterations = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setOwner(UserType value) {
        this.owner = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectType }
     *     
     */
    public ProjectType getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectType }
     *     
     */
    public void setParent(ProjectType value) {
        this.parent = value;
    }

    /**
     * Gets the value of the releases property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectReleasesType }
     *     
     */
    public ProjectReleasesType getReleases() {
        return releases;
    }

    /**
     * Sets the value of the releases property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectReleasesType }
     *     
     */
    public void setReleases(ProjectReleasesType value) {
        this.releases = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the teamMembers property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectTeamMembersType }
     *     
     */
    public ProjectTeamMembersType getTeamMembers() {
        return teamMembers;
    }

    /**
     * Sets the value of the teamMembers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectTeamMembersType }
     *     
     */
    public void setTeamMembers(ProjectTeamMembersType value) {
        this.teamMembers = value;
    }

}
