//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.17 at 11:55:40 PM EDT 
//


package com.ceb.ppm.schema.mfw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RevisionHistoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RevisionHistoryType">
 *   &lt;complexContent>
 *     &lt;extension base="{}WorkspaceDomainObjectType">
 *       &lt;sequence>
 *         &lt;element name="Revisions" type="{}RevisionHistoryRevisionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RevisionHistoryType", propOrder = {
    "revisions"
})
public class RevisionHistoryType
    extends WorkspaceDomainObjectType
{

    @XmlElement(name = "Revisions")
    protected RevisionHistoryRevisionsType revisions;

    /**
     * Gets the value of the revisions property.
     * 
     * @return
     *     possible object is
     *     {@link RevisionHistoryRevisionsType }
     *     
     */
    public RevisionHistoryRevisionsType getRevisions() {
        return revisions;
    }

    /**
     * Sets the value of the revisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RevisionHistoryRevisionsType }
     *     
     */
    public void setRevisions(RevisionHistoryRevisionsType value) {
        this.revisions = value;
    }

}
