//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.12 at 09:47:28 PM EDT 
//


package com.ceb.ppm.schema.mfw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkspaceDomainObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkspaceDomainObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{}DomainObjectType">
 *       &lt;sequence>
 *         &lt;element name="Workspace" type="{}WorkspaceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkspaceDomainObjectType", propOrder = {
    "workspace"
})
@XmlSeeAlso({
    AttachmentType.class,
    RevisionHistoryType.class,
    TestCaseStepType.class,
    BuildMetricType.class,
    AttachmentContentType.class,
    BuildType.class,
    TagType.class,
    ProjectType.class,
    ScopedAttributeDefinitionType.class,
    AttributeDefinitionType.class,
    WorkspaceConfigurationType.class,
    ChangeType.class,
    ConversationPostType.class,
    BuildDefinitionType.class,
    ReleaseType.class,
    TimeEntryItemType.class,
    ArtifactNotificationType.class,
    SCMRepositoryType.class,
    IterationType.class,
    TypeDefinitionType.class,
    ChangesetType.class,
    CumulativeFlowDataType.class,
    TestCaseResultType.class,
    BuildMetricDefinitionType.class,
    ArtifactType.class,
    RevisionType.class,
    TimeEntryValueType.class,
    UserIterationCapacityType.class
})
public class WorkspaceDomainObjectType
    extends DomainObjectType
{

    @XmlElement(name = "Workspace")
    protected WorkspaceType workspace;

    /**
     * Gets the value of the workspace property.
     * 
     * @return
     *     possible object is
     *     {@link WorkspaceType }
     *     
     */
    public WorkspaceType getWorkspace() {
        return workspace;
    }

    /**
     * Sets the value of the workspace property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkspaceType }
     *     
     */
    public void setWorkspace(WorkspaceType value) {
        this.workspace = value;
    }

}
