//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 12:50:52 PM EDT 
//

package com.ceb.ppm.schema.mfw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WorkspacePermissionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="WorkspacePermissionType">
 *   &lt;complexContent>
 *     &lt;extension base="{}UserPermissionType">
 *       &lt;sequence>
 *         &lt;element name="Workspace" type="{}WorkspaceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkspacePermissionType", propOrder = { "workspace" })
public class WorkspacePermissionType extends UserPermissionType {

	@XmlElement(name = "Workspace")
	protected WorkspaceType workspace;

	/**
	 * Gets the value of the workspace property.
	 * 
	 * @return possible object is {@link WorkspaceType }
	 * 
	 */
	public WorkspaceType getWorkspace() {
		return workspace;
	}

	/**
	 * Sets the value of the workspace property.
	 * 
	 * @param value
	 *            allowed object is {@link WorkspaceType }
	 * 
	 */
	public void setWorkspace(WorkspaceType value) {
		this.workspace = value;
	}

}
