//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.17 at 11:55:40 PM EDT 
//


package com.ceb.ppm.schema.mfw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkspaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkspaceType">
 *   &lt;complexContent>
 *     &lt;extension base="{}DomainObjectType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Owner" type="{}UserType" minOccurs="0"/>
 *         &lt;element name="Projects" type="{}WorkspaceProjectsType" minOccurs="0"/>
 *         &lt;element name="RevisionHistory" type="{}RevisionHistoryType" minOccurs="0"/>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TypeDefinitions" type="{}WorkspaceTypeDefinitionsType" minOccurs="0"/>
 *         &lt;element name="WorkspaceConfiguration" type="{}WorkspaceConfigurationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkspaceType", propOrder = {
    "description",
    "name",
    "notes",
    "owner",
    "projects",
    "revisionHistory",
    "state",
    "style",
    "typeDefinitions",
    "workspaceConfiguration"
})
public class WorkspaceType
    extends DomainObjectType
{

    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Notes")
    protected String notes;
    @XmlElement(name = "Owner")
    protected UserType owner;
    @XmlElement(name = "Projects")
    protected WorkspaceProjectsType projects;
    @XmlElement(name = "RevisionHistory")
    protected RevisionHistoryType revisionHistory;
    @XmlElement(name = "State")
    protected String state;
    @XmlElement(name = "Style")
    protected String style;
    @XmlElement(name = "TypeDefinitions")
    protected WorkspaceTypeDefinitionsType typeDefinitions;
    @XmlElement(name = "WorkspaceConfiguration")
    protected WorkspaceConfigurationType workspaceConfiguration;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setOwner(UserType value) {
        this.owner = value;
    }

    /**
     * Gets the value of the projects property.
     * 
     * @return
     *     possible object is
     *     {@link WorkspaceProjectsType }
     *     
     */
    public WorkspaceProjectsType getProjects() {
        return projects;
    }

    /**
     * Sets the value of the projects property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkspaceProjectsType }
     *     
     */
    public void setProjects(WorkspaceProjectsType value) {
        this.projects = value;
    }

    /**
     * Gets the value of the revisionHistory property.
     * 
     * @return
     *     possible object is
     *     {@link RevisionHistoryType }
     *     
     */
    public RevisionHistoryType getRevisionHistory() {
        return revisionHistory;
    }

    /**
     * Sets the value of the revisionHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link RevisionHistoryType }
     *     
     */
    public void setRevisionHistory(RevisionHistoryType value) {
        this.revisionHistory = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the typeDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link WorkspaceTypeDefinitionsType }
     *     
     */
    public WorkspaceTypeDefinitionsType getTypeDefinitions() {
        return typeDefinitions;
    }

    /**
     * Sets the value of the typeDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkspaceTypeDefinitionsType }
     *     
     */
    public void setTypeDefinitions(WorkspaceTypeDefinitionsType value) {
        this.typeDefinitions = value;
    }

    /**
     * Gets the value of the workspaceConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link WorkspaceConfigurationType }
     *     
     */
    public WorkspaceConfigurationType getWorkspaceConfiguration() {
        return workspaceConfiguration;
    }

    /**
     * Sets the value of the workspaceConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkspaceConfigurationType }
     *     
     */
    public void setWorkspaceConfiguration(WorkspaceConfigurationType value) {
        this.workspaceConfiguration = value;
    }

}
